version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-app
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_container.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: verify_app.sh
      timeout: 300
      runas: root
